python3 main.py --flagfile=config/train_tpu_oliv_att_None.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_None.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_None.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_random-crop.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_random-crop.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_random-crop.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_noise.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_noise.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_noise.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_crop_and_noise.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_crop_and_noise.cfg &&
python3 main.py --flagfile=config/train_tpu_oliv_att_crop_and_noise.cfg 
